### ISSUE TITLE
[CRASH] Crash on server start

### ISSUE THREAD

**Issue by xDiogow** [KitsuneLab-Development/K4-Arenas#18]
**Describe the crash**
The server crashes on start

**To Reproduce**
I don't know 

**Logs/Screenshots**
https://paste.tf/pastes/view/yHCaWpUlGJNoxvHDGvuOij2vS

**Environment (please complete the following information):**
- OS: [e.g., Ubuntu] Ubuntu 
- CSS Version [e.g., v153] Latest
- Plugin Version [e.g., v3.1.5] Latest
- Configs [OPTIONAL depending on the context of the bug] Default only changed mysql (The database works properly with K4-System)

**Possible Solution (optional)**
Sorry but even me I don't know why it is happenning

**Comment by K4ryuu** [comment]
What makes you think it is from Arenas?

**Comment by K4ryuu** [comment]
Also you sure this is healthy? `GameTypes: could not find matching game mode value of "" in any game type.`

**Comment by xDiogow** [comment]
> What makes you think it is from Arenas?
Since I got the same plugins on another server and it works and I tried without arenas and it runs perfectly


> Also you sure this is healthy? `GameTypes: could not find matching game mode value of "" in any game type.`
The server is freshly installed and still got some stuff to change but without arenas it works properly

**Comment by K4ryuu** [comment]
I recommend you to install the latest version of Arenas then, because there is no know bug as a crash currently. However the plugin is used in a wide range. After check also I didnt find any problem with is. Check your versions and use maps that has regular player spawns and you are good to go.  Without any details I cannot help you. Possibly you just installed the plugin without all its component.
